export const addressInfo = [
  {
    region: "Oromia",
    zone: {
      Arsi: [
        "Aminya",
        "Aseko",
        "Asella",
        "Bale Gasegar",
        "Batu Dugda",
        "Chole",
        "Digelu fi Tijo",
        "Diksis",
        "Dodota",
        "Enkelo Wabe",
        "Gololcha",
        "Guna",
        "Hetosa",
        "Jeju",
        "Lemo fi bilbilo",
        "Lode Hetosa",
        "Merti",
        "Munesa",
        "Robe",
        "Seru",
        "Sire",
        "Shirka",
        "Sude",
        "Tena",
        "Tiyo",
        "Shanan kolu",
      ],
      Bale: [
        "Agarfa",
        "Berbere",
        "Delo Menna",
        "Dinsho",
        "Gasera",
        "Goba",
        "Goro",
        "Guradamole",
        "Harena Buluk",
        "Meda Welabu",
        "Robe",
        "Sinana",
      ],
      "East Bale": [
        "Sawena",
        "Rayitu",
        "Legahidha",
        "Gindhir",
        "Dawe Qachan",
        "Dawe sarar",
        "Gololcha",
        "Gindhir",
      ],
      Borena: [
        "Arero",
        "Dillo",
        "Dire",
        "Gomole",
        "Miyu",
        "Moyale",
        "Teltele",
        "Yabelo",
        "Dubuluq",
        "Elowaye",
        "Wacile",
        "Yabelo",
        "Guchi",
        "Dhas",
      ],
      "Buno Bedele": [
        "Bedele",
        "Chora",
        "Dabo",
        "Chawaka",
        "Boracha",
        "Gechi",
        "Dedesa",
        "Dega",
        "Meko",
        "Badele",
      ],
      "East Hararghe": [
        "Babile",
        "Badeno",
        "Chinaksen",
        "Dadar",
        "Fedis",
        "Girawa",
        "Gola Oda",
        "Goro Gutu",
        "Gursum",
        "Haro Maya",
        "Jarso",
        "Kersa",
        "Haramaya",
        "Kombolcha",
        "Kurfa Chele",
        "Malka Balo",
        "Meyumuluke",
        "Meta",
        "Midega Tola",
        "Kumbi",
        "Goro muti",
      ],
      "East Shoa": [
        "Ada'a",
        "Adami Tullu and Jido Kombolcha",
        "Batu",
        "Bishoftu",
        "Bora",
        "Meki",
        "Boset",
        "Dugda",
        "Fentale",
        "Gimbichu",
        "Liben",
        "Lume",
        "Magaalaa Adaamaa",
      ],
      "East Wollega": [
        "Bonaya Boshe",
        "Diga",
        "Gida Kiremu",
        "Gobu Seyo",
        "Gudeya Bila",
        "Guto Gida",
        "Haro Limmu",
        "Ibantu",
        "Jimma Arjo",
        "Leka Dulecha",
        "Limmu",
        "Naqamte",
        "Nunu Kumba",
        "Sasiga",
        "Sibu Sire",
        "Wama Hagalo",
        "Wayu Tuka",
      ],
      "East Guji": [
        "Aga wayu",
        "Adola",
        "Ana Sora",
        "Bore",
        "Dama",
        "Girja",
        "Arda jila",
        "Liben",
        "Negele Guji",
        "Odo Shakiso",
        "Uraga",
        "Wadera",
        "Gumi Eldallo",
        "Adola Rede",
        "Gorodola",
        "Haro walabu",
        "Saba boru",
        "Shakiso",
      ],
      "Horo Guduru Welega": [
        "Abaya Chomen",
        "Abe Dongoro",
        "Amuru",
        "Guduru",
        "Hababo Guduru",
        "Horo",
        "Jardega Jarte",
        "Jimma Genete",
        "Jimma Rare",
        "Shambu",
        "Horo Bulluq",
        "Sulala Fincha",
      ],
      "Ilu Aba Bora": [
        "Ale",
        "Alge Sache",
        "Bacho",
        "Bilo Nopha",
        "Bure",
        "Darimu",
        "Didu",
        "Doreni",
        "Halu",
        "Hurumu",
        "Metu",
        "Metu",
        "Nono Sele",
        "Supena Sodo",
        "Yayu",
      ],
      Jimma: [
        "Agaro",
        "Chora Botor",
        "Dedo",
        "Gera",
        "Gomma",
        "Guma",
        "Kersa",
        "Limmu Sakka",
        "Limmu Kosa",
        "Mana",
        "Omo Nada",
        "Seka Chekorsa",
        "Setema",
        "Shebe Senbo",
        "Sigmo",
        "Sokoru",
        "Botor xolay",
        "Nadhi Gibe",
        "Mancho",
        "Nono Benja",
        "Omo beyam",
      ],
      "Qelam Wollega": [
        "Anfillo",
        "Dale Sedi",
        "Dale Wabera",
        "Dembidolo",
        "Gawo Kebe",
        "Gidami",
        "Hawa Gelan",
        "Jimma Horo",
        "Lalo Kile",
        "Sayo",
        "Yemalogi Welele",
        "Sedi Chenka",
      ],
      "North Shoa": [
        "Abichu",
        "Aleltu",
        "Degem",
        "Dera",
        "Fiche",
        "Girar Jarso",
        "Hidabu Abote",
        "Jida",
        "Kembibit",
        "Kuyu",
        "Liban",
        "Wara Jarso",
        "Wuchale",
        "Yaya Gulele",
      ],
      "Southwest Shoa": [
        "Amaya",
        "Becho",
        "Dawo",
        "Ilu",
        "Goro",
        "Kersa fi Malima",
        "Seden Sodo",
        "Sodo Dachi",
        "Tole",
        "Waliso",
        "Waliso",
        "Wanchi",
      ],
      "West Arsi": [
        "Adaba",
        "Negele Arsi",
        "Dodola",
        "Gedeb Hassasa",
        "Kofele",
        "Kokosa",
        "Qoree",
        "Naannawa Shashamane",
        "Nensebo",
        "Seraro",
        "Shala",
        "Shashamane",
        "Heban Arsi",
        "Dodola",
        "Kofale",
        "Nagele Arsi",
      ],
      Sheger: ["Gelan"],
      "West Guji": [
        "Bule Hora",
        "Birbirsa Kojowa",
        "Kerca",
        "Abeya",
        "Suro",
        "Gelana",
        "Dugda dawa",
        "Hambala wamana",
        "Bulehora",
        "Karcha",
        "Malka soda",
      ],
      "West Hararghe": [
        "Badessa",
        "Boke",
        "Oda Bultum",
        "Char char",
        "Chiro",
        "Daru labu",
        "Doba",
        "Gamachis",
        "Guba Koricha",
        "Habro",
        "Kuni",
        "Masela",
        "Mieso",
        "Nannawa Chiro",
        "Tulo",
        "Gumbi bordode",
        "Burqa Dhintu",
        "Mechara michata",
      ],
      "West Shoa": [
        "Abuna Ginde Beret",
        "Ada'a Berga",
        "Ambo",
        "Bako Tibe",
        "Cheliya",
        "Dano",
        "Dendi",
        "Dire Enchini",
        "Ejerie",
        "Ejersa Lafo",
        "Elfata",
        "Ginde Beret",
        "Jeldu",
        "Jibat",
        "Meta Robi",
        "Midakegn",
        "Naannawa Ambo",
        "Nono",
        "Toke Kutaye",
        "Liban Jawi",
        "Cobii",
        "Ilu Galan",
        "Ambo",
      ],
      "West Wollega": [
        "Ayra",
        "Babo Gambela",
        "Begi",
        "Boji Chokorsa",
        "Boji Dirmaji",
        "Genji",
        "Gimbi",
        "Gimbi",
        "Guliso",
        "Haru",
        "Homa",
        "Jarso",
        "Kondala",
        "Kiltu Kara",
        "Lalo Asabi",
        "Mana Sibu",
        "Nejo",
        "Nole Kaba",
        "Sayo Nole",
        "Yubdo",
      ],
      "Adama Special Zone": ["Adama"],
      "Jimma Special Zone": ["Jimma"],
      "Oromia Special Zone Surrounding Finfinne": [
        "Akaki",
        "Bereh",
        "Burayu",
        "Holeta",
        "Koye Feche",
        "Mulo",
        "Sebeta Hawas",
        "Sendafa",
        "Sululta",
        "Walmara",
      ],
    },
  },
  {
    region: "Addis Ababa",
    zone: {
      "Addis Ketema": [
        "Woreda 1",
        "Woreda 2",
        "Woreda 3",
        "Woreda 4",
        "Woreda 5",
        "Woreda 6",
        "Woreda 7",
        "Woreda 8",
        "Woreda 9",
        "Woreda 10",
      ],
      "Akaky Kaliti": [
        "Woreda 1",
        "Woreda 2",
        "Woreda 3",
        "Woreda 4",
        "Woreda 5",
        "Woreda 6",
        "Woreda 7",
        "Woreda 8",
        "Woreda 9",
        "Woreda 10",
        "Woreda 11",
      ],
      Arada: [
        "Woreda 1",
        "Woreda 2",
        "Woreda 3",
        "Woreda 4",
        "Woreda 5",
        "Woreda 6",
        "Woreda 7",
      ],
      Bole: [
        "Woreda 1",
        "Woreda 2",
        "Woreda 3",
        "Woreda 4",
        "Woreda 5",
        "Woreda 6",
        "Woreda 7",
        "Woreda 8",
        "Woreda 9",
        "Woreda 10",
        "Woreda 11",
        "Woreda 12",
        "Woreda 13",
        "Woreda 14",
      ],
      Gulele: [
        "Woreda 1",
        "Woreda 2",
        "Woreda 3",
        "Woreda 4",
        "Woreda 5",
        "Woreda 6",
        "Woreda 7",
        "Woreda 8",
        "Woreda 9",
        "Woreda 10",
      ],
      kirkos: [
        "Woreda 1",
        "Woreda 2",
        "Woreda 3",
        "Woreda 4",
        "Woreda 5",
        "Woreda 6",
        "Woreda 7",
        "Woreda 8",
        "Woreda 9",
        "Woreda 10",
        "Woreda 11",
      ],
      "Lemi-kura": [
        "Woreda 1",
        "Woreda 2",
        "Woreda 3",
        "Woreda 4",
        "Woreda 5",
        "Woreda 6",
        "Woreda 7",
        "Woreda 8",
        "Woreda 9",
        "Woreda 10",
      ],
      Lideta: [
        "Woreda 1",
        "Woreda 2",
        "Woreda 3",
        "Woreda 4",
        "Woreda 5",
        "Woreda 6",
        "Woreda 7",
        "Woreda 8",
        "Woreda 9",
        "Woreda 10",
      ],
      "Nifas Silk-lafto": [
        "Woreda 1",
        "Woreda 2",
        "Woreda 3",
        "Woreda 4",
        "Woreda 5",
        "Woreda 6",
        "Woreda 7",
        "Woreda 8",
        "Woreda 9",
        "Woreda 10",
        "Woreda 11",
        "Woreda 12",
      ],
      Yeka: [
        "Woreda 1",
        "Woreda 2",
        "Woreda 3",
        "Woreda 4",
        "Woreda 5",
        "Woreda 6",
        "Woreda 7",
        "Woreda 8",
        "Woreda 9",
        "Woreda 10",
        "Woreda 11",
        "Woreda 12",
        "Woreda 13",
        "Woreda 14",
      ],
    },
  },
];
