export const userActionTypes = {
  SET_TOKEN: "SET_TOKEN",
  REFRESH_TOKEN: "REFRESH_TOKEN",
  TOGGLE_ROLE: "TOGGLE_ROLE",
  SET_UNION_ID: "SET_UNION_ID",
  SET_PRCOOPERATIVE_ID: "SET_PRCOOPERATIVE_ID",
  SET_USER_PROFILE: "SET_USER_PROFILE",

};
