export const dataTry = [
  {
    unionName: "yared",
    address: {
      addressId: 4,
      country: null,
      region: "oromia",
      zone: "West_Guji",
      woreda: "Kerca",
      town: "Yebu",
      kebele: "Cafe Donsa",
      email: "yaredbest81@gmail.com",
      phoneNumber: "0932308204",
    },
    type: {
      typeId: 1,
      typeName: "type010",
      type: "UN",
    },
    sector: {
      sectorId: 4,
      name: "sector 1",
    },
    no_of_ActivePrCooperatives: 1,
    no_of_Non_ActivePrCooperatives: 1,
    total_No_of_PrCooperatives: 3,
    no_of_Female_Individual_Member: 0,
    no_of_Male_Individual_Member: 0,
    accountInfos: [],
    yearOfStablishment: "2023-03-13",
    no_of_Female_Stablishing_Member: 0,
    no_of_Male_Stablishing_Member: 0,
    no_of_Total_Stablishing_Member: 0,
    shareCapitalUponEstablishmnet: 21656263.5,
    annualTurnOvers: [],
    assets: [
      {
        assetName: "Asset 7",
        value: 80000000,
        type: "UN",
      },
    ],
    liabilities: [],
    paidUpShares: [
      {
        paidUpValue: 368569652,
        dateGenerated: "2023-04-05",
      },
      {
        paidUpValue: 1268532,
        dateGenerated: "2023-04-11",
      },
    ],
    osLoans: [
      {
        osLoanValue: 68796453,
        dateGenerated: "2023-03-29",
      },
      {
        osLoanValue: 256986536,
        dateGenerated: "2023-04-05",
      },
      {
        osLoanValue: 965,
        dateGenerated: "2023-04-04",
      },
    ],
    total_no_of_Individual_Member: 0,
    commodities: [
      {
        commodityName: "commodity 12",
        type: "UN",
      },
    ],
  },
  {
    unionName: "abdu jemal 2",
    address: {
      addressId: 22,
      country: null,
      region: "oromia",
      zone: "West_Arsi",
      woreda: "Negele Arsi",
      town: "addis ababa",
      kebele: "dsfdg",
      email: "abdumussema22@gmail.com",
      phoneNumber: "0946514836",
    },
    type: {
      typeId: 52,
      typeName: "type0101",
      type: "UN",
    },
    sector: {
      sectorId: 4,
      name: "sector 1",
    },
    no_of_ActivePrCooperatives: 0,
    no_of_Non_ActivePrCooperatives: 0,
    total_No_of_PrCooperatives: 2,
    no_of_Female_Individual_Member: 0,
    no_of_Male_Individual_Member: 1,
    accountInfos: [
      {
        branch: "Bole Rwanada",
        district: "West Finfine",
        accountNumber: "10002212231",
        accountBalances: [
          {
            accountBalanceId: 1,
            accountBalance: 1022.23,
            dateGenerated: "2023-03-31",
            account: {
              accountId: 1,
              accountNumber: "10002212231",
              accountType: "Saving edited",
              branch: "Bole Rwanada",
              district: "West Finfine",
              union: {
                unionId: 52,
                name: "abdu jemal 2",
                dateOfEstablishmnet: "2023-04-07",
                shareCapitalUponEstablishmnet: 15986532,
                isActive: true,
                address: {
                  addressId: 22,
                  country: null,
                  region: "oromia",
                  zone: "West_Arsi",
                  woreda: "Negele Arsi",
                  town: "addis ababa",
                  kebele: "dsfdg",
                  email: "abdumussema22@gmail.com",
                  phoneNumber: "0946514836",
                },
                type: {
                  typeId: 52,
                  typeName: "type0101",
                  type: "UN",
                },
                sector: {
                  sectorId: 4,
                  name: "sector 1",
                },
              },
              prCooperative: null,
            },
          },
        ],
      },
    ],
    yearOfStablishment: "2023-04-07",
    no_of_Female_Stablishing_Member: 0,
    no_of_Male_Stablishing_Member: 0,
    no_of_Total_Stablishing_Member: 0,
    shareCapitalUponEstablishmnet: 15986532,
    annualTurnOvers: [],
    assets: [
      {
        assetName: "Asset 5",
        value: 50000000,
        type: "priCooperative",
      },
      {
        assetName: "Asset 6",
        value: 50000000,
        type: "priCooperative",
      },
      {
        assetName: "Asset 4",
        value: 50000000,
        type: "UN",
      },
    ],
    liabilities: [
      {
        liabilityValue: 2653526.55,
        dateGenerated: "2023-04-13",
      },
    ],
    paidUpShares: [
      {
        paidUpValue: 12000,
        dateGenerated: "2023-04-04",
      },
    ],
    osLoans: [
      {
        osLoanValue: 5421,
        dateGenerated: "2023-04-04",
      },
      {
        osLoanValue: 859846,
        dateGenerated: "2023-04-07",
      },
    ],
    total_no_of_Individual_Member: 1,
    commodities: [
      {
        commodityName: "commodity edited",
        type: "UN",
      },
    ],
  },
  {
    unionName: "abdu jemal we",
    address: {
      addressId: 23,
      country: null,
      region: "oromia",
      zone: "West_Guji",
      woreda: "Birbirsa Kojowa",
      town: "addis ababa",
      kebele: "01",
      email: "abdumussema22@gmail.com",
      phoneNumber: "0946514836",
    },
    type: {
      typeId: 1,
      typeName: "type010",
      type: "UN",
    },
    sector: {
      sectorId: 4,
      name: "sector 1",
    },
    no_of_ActivePrCooperatives: 0,
    no_of_Non_ActivePrCooperatives: 0,
    total_No_of_PrCooperatives: 0,
    no_of_Female_Individual_Member: 0,
    no_of_Male_Individual_Member: 0,
    accountInfos: [],
    yearOfStablishment: "2023-04-04",
    no_of_Female_Stablishing_Member: 0,
    no_of_Male_Stablishing_Member: 0,
    no_of_Total_Stablishing_Member: 0,
    shareCapitalUponEstablishmnet: 125,
    annualTurnOvers: [],
    assets: [
      {
        assetName: "Asset 12",
        value: 50000000,
        type: "UN",
      },
    ],
    liabilities: [
      {
        liabilityValue: 3743.23,
        dateGenerated: "2023-09-04",
      },
    ],
    paidUpShares: [
      {
        paidUpValue: 65489465,
        dateGenerated: "2023-04-06",
      },
    ],
    osLoans: [],
    total_no_of_Individual_Member: 0,
    commodities: [
      {
        commodityName: "abdy",
        type: "UN",
      },
    ],
  },
  {
    unionName: "abdu jemal",
    address: {
      addressId: 25,
      country: null,
      region: "oromia",
      zone: "Jimma",
      woreda: "Sigmo",
      town: "addis ababa",
      kebele: "01",
      email: "abdumussema22@gmail.com",
      phoneNumber: "0946514836",
    },
    type: {
      typeId: 1,
      typeName: "type010",
      type: "UN",
    },
    sector: {
      sectorId: 2,
      name: "sector 2",
    },
    no_of_ActivePrCooperatives: 0,
    no_of_Non_ActivePrCooperatives: 0,
    total_No_of_PrCooperatives: 0,
    no_of_Female_Individual_Member: 1,
    no_of_Male_Individual_Member: 5,
    accountInfos: [],
    yearOfStablishment: "2023-04-04",
    no_of_Female_Stablishing_Member: 0,
    no_of_Male_Stablishing_Member: 0,
    no_of_Total_Stablishing_Member: 0,
    shareCapitalUponEstablishmnet: 15986532,
    annualTurnOvers: [],
    assets: [
      {
        assetName: "sdafgf",
        value: 205558.32,
        type: "UN",
      },
      {
        assetName: "dfdfdafdfd",
        value: 256565.32,
        type: "UN",
      },
      {
        assetName: "Abdusemed1",
        value: 205558.32,
        type: "priCooperative",
      },
    ],
    liabilities: [
      {
        liabilityValue: 1515001,
        dateGenerated: "2023-04-06",
      },
    ],
    paidUpShares: [],
    osLoans: [],
    total_no_of_Individual_Member: 6,
    commodities: [
      {
        commodityName: "hey there one",
        type: "UN",
      },
    ],
  },
  {
    unionName: "abdu jemal faa",
    address: {
      addressId: 38,
      country: null,
      region: "oromia",
      zone: "Jimma",
      woreda: "Sigmo",
      town: "addis ababa",
      kebele: "01",
      email: "abdumussema22@gmail.com",
      phoneNumber: "0946514836",
    },
    type: {
      typeId: 1,
      typeName: "type010",
      type: "UN",
    },
    sector: {
      sectorId: 2,
      name: "sector 2",
    },
    no_of_ActivePrCooperatives: 0,
    no_of_Non_ActivePrCooperatives: 0,
    total_No_of_PrCooperatives: 0,
    no_of_Female_Individual_Member: 0,
    no_of_Male_Individual_Member: 0,
    accountInfos: [],
    yearOfStablishment: "2023-04-04",
    no_of_Female_Stablishing_Member: 0,
    no_of_Male_Stablishing_Member: 0,
    no_of_Total_Stablishing_Member: 0,
    shareCapitalUponEstablishmnet: 15986532,
    annualTurnOvers: [],
    assets: [],
    liabilities: [],
    paidUpShares: [],
    osLoans: [],
    total_no_of_Individual_Member: 0,
    commodities: [],
  },
  {
    unionName: "union 5",
    address: {
      addressId: 62,
      country: null,
      region: "oromia",
      zone: "Arsi",
      woreda: "Merti",
      town: "Bekoji",
      kebele: "01",
      email: "union@gmail.com",
      phoneNumber: "911111111",
    },
    type: {
      typeId: 1,
      typeName: "type010",
      type: "UN",
    },
    sector: {
      sectorId: 1,
      name: "fdffd",
    },
    no_of_ActivePrCooperatives: 1,
    no_of_Non_ActivePrCooperatives: 0,
    total_No_of_PrCooperatives: 1,
    no_of_Female_Individual_Member: 0,
    no_of_Male_Individual_Member: 2,
    accountInfos: [],
    yearOfStablishment: "2023-03-29",
    no_of_Female_Stablishing_Member: 0,
    no_of_Male_Stablishing_Member: 0,
    no_of_Total_Stablishing_Member: 0,
    shareCapitalUponEstablishmnet: 23500123.5,
    annualTurnOvers: [],
    assets: [],
    liabilities: [],
    paidUpShares: [
      {
        paidUpValue: 876542,
        dateGenerated: "2023-04-03",
      },
    ],
    osLoans: [
      {
        osLoanValue: 3687543,
        dateGenerated: "2023-04-11",
      },
    ],
    total_no_of_Individual_Member: 2,
    commodities: [],
  },
  {
    unionName: "fsdfykgjh",
    address: {
      addressId: 78,
      country: null,
      region: "oromia",
      zone: "West_Harerghe",
      woreda: "Char char",
      town: "addis ababa",
      kebele: "456",
      email: "abdumussema22@gmail.com",
      phoneNumber: "0946514836",
    },
    type: {
      typeId: 1,
      typeName: "type010",
      type: "UN",
    },
    sector: {
      sectorId: 1,
      name: "fdffd",
    },
    no_of_ActivePrCooperatives: 2,
    no_of_Non_ActivePrCooperatives: 0,
    total_No_of_PrCooperatives: 4,
    no_of_Female_Individual_Member: 2,
    no_of_Male_Individual_Member: 3,
    accountInfos: [
      {
        branch: "finfinne",
        district: "dugd",
        accountNumber: "1022200133177",
        accountBalances: [],
      },
      {
        branch: "finfinne",
        district: "hello",
        accountNumber: "1000",
        accountBalances: [],
      },
      {
        branch: "finfinne",
        district: "rwanda",
        accountNumber: "568565",
        accountBalances: [],
      },
    ],
    yearOfStablishment: "2023-04-19",
    no_of_Female_Stablishing_Member: 0,
    no_of_Male_Stablishing_Member: 0,
    no_of_Total_Stablishing_Member: 0,
    shareCapitalUponEstablishmnet: 4356,
    annualTurnOvers: [
      {
        annualTurnOverValue: 10000,
        dateGenerated: "2023-04-05",
      },
      {
        annualTurnOverValue: 212121,
        dateGenerated: "2023-04-30",
      },
      {
        annualTurnOverValue: 100032,
        dateGenerated: "2023-04-05",
      },
      {
        annualTurnOverValue: 2222223,
        dateGenerated: "2023-04-12",
      },
      {
        annualTurnOverValue: 4353454,
        dateGenerated: "2023-04-11",
      },
      {
        annualTurnOverValue: 544,
        dateGenerated: "2023-04-12",
      },
    ],
    assets: [
      {
        assetName: "hello",
        value: 256565.32,
        type: "UN",
      },
      {
        assetName: "Abdusemed1dq",
        value: 256565.32,
        type: "UN",
      },
      {
        assetName: "dghj",
        value: 78676,
        type: "UN",
      },
    ],
    liabilities: [
      {
        liabilityValue: 448554401,
        dateGenerated: "2023-04-06",
      },
    ],
    paidUpShares: [
      {
        paidUpValue: 2666666,
        dateGenerated: "2023-03-31",
      },
      {
        paidUpValue: 2666666,
        dateGenerated: "2023-03-31",
      },
      {
        paidUpValue: 12000000,
        dateGenerated: "2023-03-31",
      },
    ],
    osLoans: [
      {
        osLoanValue: 200001,
        dateGenerated: "2023-02-05",
      },
      {
        osLoanValue: 200000011,
        dateGenerated: "2023-02-05",
      },
    ],
    total_no_of_Individual_Member: 5,
    commodities: [
      {
        commodityName: "abdy",
        type: "UN",
      },
      {
        commodityName: "hey there",
        type: "UN",
      },
      {
        commodityName: "454201",
        type: "UN",
      },
    ],
  },
];

export const unionFakeData = [
  {
    unionId: 2,
    name: "union 2",
    dateOfEstablishmnet: "2023-03-29",
    shareCapitalUponEstablishmnet: 23500123.5,
    isActive: true,
    address: {
      addressId: 4,
      country: null,
      region: "Oromia",
      zone: "Arsi",
      woreda: "Bekoji",
      town: "Bekoji",
      kebele: "01",
      email: "union@gmail.com",
      phoneNumber: "911111111",
    },
    type: {
      typeId: 1,
      typeName: "type edited",
      type: "UN",
    },
    sector: {
      sectorId: 1,
      name: "sctore edited",
    },
  },
  {
    unionId: 1,
    name: "union edited",
    dateOfEstablishmnet: "2023-03-29",
    shareCapitalUponEstablishmnet: 23500123.5,
    isActive: true,
    address: {
      addressId: 5,
      country: null,
      region: "Oromia",
      zone: "Arsi",
      woreda: "Bekoji",
      town: "Bekoji",
      kebele: "01",
      email: "union@gmail.com",
      phoneNumber: "911111111",
    },
    type: {
      typeId: 1,
      typeName: "type edited",
      type: "UN",
    },
    sector: {
      sectorId: 1,
      name: "sctore edited",
    },
  },
];

export const prFakeData = [
  {
    prCooperativeId: 2,
    name: "prCooperative 2",
    dateOfEstablishmnet: "2023-03-31",
    shareCapitalUponEstablishmnet: 250000,
    isActive: true,
    address: {
      addressId: 15,
      country: null,
      region: "Oromia",
      zone: "Arsi",
      woreda: "nagele",
      town: "nagele",
      kebele: "10",
      email: "prCooperative@gmail.com",
      phoneNumber: "9222222222",
    },
    type: {
      typeId: 1,
      typeName: "type01",
      type: "UN",
    },
    sector: {
      sectorId: 1,
      name: "fdff",
    },
    union: {
      unionId: 1,
      name: "union 2",
      dateOfEstablishmnet: "2023-03-29",
      shareCapitalUponEstablishmnet: 23500123.5,
      isActive: true,
      address: {
        addressId: 3,
        country: null,
        region: "Oromia",
        zone: "Arsi",
        woreda: "Bekoji",
        town: "Bekoji",
        kebele: "01",
        email: "union@gmail.com",
        phoneNumber: "911111111",
      },
      type: {
        typeId: 1,
        typeName: "type01",
        type: "UN",
      },
      sector: {
        sectorId: 1,
        name: "fdff",
      },
    },
  },
  {
    prCooperativeId: 1,
    name: "prCoop 3",
    dateOfEstablishmnet: "2023-03-31",
    shareCapitalUponEstablishmnet: 9850000,
    isActive: false,
    address: {
      addressId: 16,
      country: null,
      region: "Oromia",
      zone: "Arsi",
      woreda: "nagele",
      town: "nagele",
      kebele: "10",
      email: "prCooperative@gmail.com",
      phoneNumber: "9222222222",
    },
    type: {
      typeId: 1,
      typeName: "type01",
      type: "UN",
    },
    sector: {
      sectorId: 1,
      name: "fdff",
    },
    union: {
      unionId: 1,
      name: "union 2",
      dateOfEstablishmnet: "2023-03-29",
      shareCapitalUponEstablishmnet: 23500123.5,
      isActive: true,
      address: {
        addressId: 3,
        country: null,
        region: "Oromia",
        zone: "Arsi",
        woreda: "Bekoji",
        town: "Bekoji",
        kebele: "01",
        email: "union@gmail.com",
        phoneNumber: "911111111",
      },
      type: {
        typeId: 1,
        typeName: "type01",
        type: "UN",
      },
      sector: {
        sectorId: 1,
        name: "fdff",
      },
    },
  },
  {
    prCooperativeId: 52,
    name: "prCoop4",
    dateOfEstablishmnet: "2023-03-31",
    shareCapitalUponEstablishmnet: 250000,
    isActive: true,
    address: {
      addressId: 17,
      country: null,
      region: "Oromia",
      zone: "Arsi",
      woreda: "nagele",
      town: "nagele",
      kebele: "10",
      email: "prCooperative@gmail.com",
      phoneNumber: "9222222222",
    },
    type: {
      typeId: 1,
      typeName: "type01",
      type: "UN",
    },
    sector: {
      sectorId: 1,
      name: "fdff",
    },
    union: {
      unionId: 1,
      name: "union 2",
      dateOfEstablishmnet: "2023-03-29",
      shareCapitalUponEstablishmnet: 23500123.5,
      isActive: true,
      address: {
        addressId: 3,
        country: null,
        region: "Oromia",
        zone: "Arsi",
        woreda: "Bekoji",
        town: "Bekoji",
        kebele: "01",
        email: "union@gmail.com",
        phoneNumber: "911111111",
      },
      type: {
        typeId: 1,
        typeName: "type01",
        type: "UN",
      },
      sector: {
        sectorId: 1,
        name: "fdff",
      },
    },
  },
];
